application: simplelifestream
version: 1
runtime: python
api_version: 1

derived_file_type:
- python_precompiled

handlers:
- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico
  mime_type: image/x-icon

- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt

- url: /static
  static_dir: static

- url: /js/lifestream\.js
  script: api.py

- url: /app_worker/.*
  script: worker.py

- url: /test
  script: test.py

- url: /test/.*
  script: test.py
  
- url: /.*
  script: main.py
